### ISSUE TITLE
Integration with Wasmer

### ISSUE THREAD

**Issue by syrusakbary** [alexcrichton/cargo-wasi#3]
First, great work on the package!

I'd love to have Wasmer [server-side WebAssembly runtime](https://github.com/wasmerio/wasmer) available for users of `cargo-wasi`, as I think it will very useful for them to test and run WASI files with our runtime with different backends (regarding speed, for example, for benchmarking).

What would be required in our side to make this possible?

Keep up the great work!

**Comment by alexcrichton** [comment]
Thanks for the report, but this is a very early-stages project so a lot is still in flux. I'll see what I can do once this is further along, I'm still just developing this for personal use right now.
