### ISSUE TITLE
Get working binaries of `wasm-opt` for Linux

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/cargo-wasi#4]
Precompiled ones segfault everywhere!

**Comment by est31** [comment]
Ubuntu/Debian's [binaryen](https://packages.debian.org/buster/binaryen) package contains binaries that work for me. I installed them via `apt install` but the .deb files can also be manually downloaded: http://ftp.us.debian.org/debian/pool/main/b/binaryen/binaryen_68-1_amd64.deb
